#!/usr/bin/python3
import os
import sys
path = os.path.dirname(os.path.realpath(__file__))
path = os.path.realpath(os.path.join(path, 'confluent', 'confluent_server'))
sys.path.append(path)
import confluent.config.attributes as attr

with open('docs/user_reference/node_attributes.md', 'w', encoding='utf-8') as outf:
    outf.write('# Node Attributes\n\n')
    outf.write('Confluent uses a variety of attributes on nodes to be configured and provide information.  The currently recognized attributes are as follows.\n\n')
    previous_category  = None
    for field in sorted(attr.node):
        category = field.split('.')[0]
        if category != previous_category:
            outf.write(f'\n## {category}\n')
            previous_category = category

        outf.write(f'\n### {field}\n\n: {attr.node[field]['description']}\n')
        # Optionally write valid values if they exist
        if 'validvalues' in attr.node[field]:
            valid_vals = attr.node[field]['validvalues']
            values_formatted = ', '.join(str(v) for v in valid_vals)
            outf.write(f"\n: **Valid values:** {values_formatted}\n")

