#!/bin/bash
cd `dirname $0`
mkdir -p docs/manuals
cat << EOF > docs/manuals/index.md
# Confluent command man pages

EOF
cd confluent/confluent_client/
python3 addattribs.py
cd -
#cd confluent/confluent_client/doc/man/
#./buildindex.sh
#cd -
for page in confluent/confluent_client/doc/man/*.ronn; do
    cmdname=$(basename $page)
    cmdname=${cmdname%.ronn}
    echo "* [$cmdname]($cmdname)" >> docs/manuals/index.md
    cat << EOF > docs/manuals/${cmdname%.ronn}.md
---
title: Manual for $cmdname
---

EOF
    ronn --pipe --markdown $page >> docs/manuals/${cmdname%.ronn}.md &
done
wait

    

