nav:
  # Confluent deployment and discovery
  - confluentosdeploy.md
  - confluentosdeployment.md
  - confluentlimitationsosdeploy.md
  - confluentdiscoverysetting.md
  - confluentnodeassign.md
  - confluentswitchdisco.md
  - confluentenclosuredisco.md
  - collective.md
  - remoteconfluent.md
  - driverupdatemedia.md
  - nodemedia_caveats.md
  - switchtonginx.md
