nav:
  - Home: index.md
  - Getting Started: getting_started
  - User Reference: user_reference
  - Advanced Topics: advanced_topics
  - Miscellaneous: miscellaneous
  - Manuals: manuals
  - Troubleshooting: troubleshooting
  - Downloads: downloads.md
  - Release Notes: release_notes
  - Tags: tags.md
  - Archive: archive
