name: build
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: write
jobs:
  build_and_deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v5
        with:
          key: mkdocs-materialx-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-materialx-
      - name: Install MaterialX requirements
        run: pip install -r requirements.txt
      - name: Install man pages and social cards requirements
        run: sudo apt-get install -y --no-install-recommends --no-install-suggests ronn libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Unlink confluent symlink
        run: unlink confluent
      - name: Checkout confluent repository for nodeattrib and man pages
        uses: actions/checkout@v6
        with:
          repository: xcat2/confluent
          path: confluent
      - name: Make nodeattrib document
        run: python3 makeattribdoc
      - name: Make man pages
        run: bash makeman
      - name: Build (PR validation)
        if: github.event_name == 'pull_request'
        env:
          SOCIAL_CARDS: true
        run: properdocs build --strict
      - name: Build and deploy to GitHub Pages
        if: github.event_name == 'push'
        env:
          SOCIAL_CARDS: true
        run: properdocs gh-deploy --force --strict
