name: ci 
on:
  push:
    branches:
      - master
      - main
      - mkdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Material for MkDocs requirements
        run: pip install -r requirements.txt
      - name: Install Ronn for man pages
        run: sudo apt-get install -y --no-install-recommends --no-install-suggests ronn
      - name: Unlink confluent symlink
        run: unlink confluent
      - name: Checkout confluent repository for nodeattrib and man pages
        uses: actions/checkout@v4
        with:
          repository: xcat2/confluent
          path: confluent
      - name: Make nodeattrib document
        run: python3 makeattribdoc
      - name: Make man pages
        run: bash makeman
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
